server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb:http://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
        - id: carteVirtuelle-service
          uri: lb:http://CARTEVIRTUELLE-SERVICE
          predicates:
            - Path=/api/v1/carteVirtuelles/**
        - id: transaction-service
          uri: lb:http://TRANSACTION-SERVICE
          predicates:
            - Path=/api/v1/transaction/**


