spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: user-service

env:
  twilio:
    sms:
      authToken: ${AUTH_TOKEN:x}
      accountSid: ${ACCOUNT_SID:x}
      fromNo: ${FROM_NUMBER:x}


