spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: batch-service

  data:
    mongodb:
      uri: mongodb://bankatidb:bankatidb@mongodb:27017/batch?authSource=admin


  profiles:
    active: dev  # ou le profil que vous souhaitez activer
