spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: notification-service


env:
  twilio:
    sms:
      authToken: ${AUTH_TOKEN:f6dfe458258a76c5e83774179fb2e75a}
      accountSid: ${ACCOUNT_SID:AC8c9b77171a457bf6fc8e72a5506f7d06}
      fromNo: ${FROM_NUMBER:+17756183795}
